\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{Cours}[2018/03/04 v0.2]
\LoadClass{scrbook}

\RequirePackage[margin=1cm]{geometry}
\RequirePackage{fontspec}
\setmainfont[Mapping=tex-text]{Source Serif Pro Regular}
\setsansfont[Mapping=tex-text]{Source Sans Pro Regular}
\RequirePackage[frenchb]{babel}
\RequirePackage[detect-all]{siunitx}
\sisetup{locale = FR,per-mode = symbol}
\RequirePackage{graphicx}
\RequirePackage[table]{xcolor}
\RequirePackage{tabularx}
\RequirePackage{multirow}
\RequirePackage{tikz}
\RequirePackage{pdfpages}
