\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{Programmation}[2018/02/27 v1]
\LoadClass[8pt,landscape]{extarticle}

\usepackage{luatex85}
\usepackage{geometry}
\geometry{a4paper,margin=5mm}
\usepackage[french]{babel}
\usepackage{fontspec}
\setmainfont[BoldFont = {Source Sans Pro Semi Bold}]{Source Sans Pro Light}
\usepackage{microtype}
\usepackage{xcolor}
\usepackage{colortbl}
\usepackage{booktabs}
\usepackage{tabularx}
\usepackage{hyperref}
\hypersetup{%
  unicode=true%
}

\definecolor{terre}{HTML}{C55A11}
\definecolor{nutveg}{HTML}{548235}
\definecolor{activites}{HTML}{FFC000}
\definecolor{SVTG}{HTML}{F4B183}
\definecolor{nutani}{HTML}{385724}
\definecolor{digestion}{HTML}{FFD966}
\definecolor{eres}{HTML}{FBE5D6}
\definecolor{repro}{HTML}{00B050}
\definecolor{micro}{HTML}{F8CBAD}
\definecolor{mc}{HTML}{203864}
\definecolor{genet}{HTML}{92D050}
\definecolor{immuno}{HTML}{FF0000}
\definecolor{risque}{HTML}{9DC3E6}
\definecolor{evo}{HTML}{FFFF00}
\definecolor{reprohum}{HTML}{FF99CC}
\definecolor{ressources}{HTML}{DEEBF7}